### ISSUE TITLE
media_model in Temporary Upload

### ISSUE THREAD

**Issue by dseeger** [spatie/laravel-medialibrary-pro-app#11]
Hi Freek

I moved the issue from medialibrary to here.

> In media library pro - Spatie\MediaLibraryPro\Models\TemporaryUpload
> the media Model set in config/media-library.php is not used. Instead it uses Spatie\MediaLibrary\MediaCollections\Models\Media, ignoring the config setting.
> 
> Can that be changed?

The reason this affects me is once more that I use spatie/multitenancy.
So I have a media model that extends Spatie\MediaLibrary\MediaCollections\Models\Media and uses UsesTenantConnection. Without that, when uploading a file I get the problem that the application is looking for a media table in the landlord database. So therefor it would help me if the medie model used in TemporaryUpload would be the one set in the config file.

**Comment by freekmurze** [comment]
That's indeed a good use case.

If you need this quick, I'd accept a PR that fixes this. Otherwise, I'll make this change in the next couple of weeks.

**Comment by freekmurze** [comment]
This has been fixed in the latest version.

**Comment by dseeger** [comment]
Wow, that was a quick couple of weeks! 
Thanks for the fast and friendly support! Huge fan of Spatie packages here!!
