### ISSUE TITLE
Thumbnail not showing

### ISSUE THREAD

**Issue by Robinvm** [spatie/laravel-medialibrary-pro-app#14]
Ive implemented the medialibrary, uploading works great, the thumbnail shows. But as soon as i refresh the page, the thumbnail does not show anymore, it is saved correctly. I use Vue2 and use the pro version.

In the demo app it does work so i dont understand what im doing wrong.

**Comment by Robinvm** [comment]
When i echo what i get back its `[ { "id": 4, "model_type": "Qubiqx\\Qcommerce\\Models\\Page", "model_id": 3, "uuid": "950a22d8-e7e4-4395-ab84-80ceb52cf9d1", "collection_name": "meta-image-nl", "name": "Qubiqx - logo concept 3.0 - lil.png", "file_name": "Qubiqx---logo-concept-3.0---lil.png", "mime_type": "image/png", "disk": "qcommerce", "conversions_disk": "qcommerce", "size": 58939, "manipulations": [], "custom_properties": { "alt": "sdfg" }, "generated_conversions": [], "responsive_images": [], "order_column": 0, "created_at": "2020-12-23T19:40:13.000000Z", "updated_at": "2020-12-23T19:40:18.000000Z" } ] `

But when i do it in the demo app it contains preview_url, i think that is whats wrong

`{"39a68da2-cba0-43ee-b65a-20adcc40449c":{"name":"1800px` Jacv2.jpg","file_name":"1800px-JacV20170612-Kasteelv2.jpg","uuid":"39a68da2-cba0-43ee-b65a-20adcc40449c","preview_url":"http:\/\/laravel-medialibrary-pro-app.robin\/storage\/4\/conversions\/1800px-JacV20170612-Kasteelv2-preview.jpg","original_url":"http:\/\/laravel-medialibrary-pro-app.robin\/storage\/4\/1800px-JacV20170612-Kasteelv2.jpg","order":0,"custom_properties":[],"extension":"jpg","size":384460},"65444de6-476c-4cff-bb8b-7b8aea65470d":{"name":"Q only fingerprint.png","file_name":"Q-only-fingerprint.png","uuid":"65444de6-476c-4cff-bb8b-7b8aea65470d","preview_url":"http:\/\/laravel-medialibrary-pro-app.robin\/storage\/6\/conversions\/Q-only-fingerprint-preview.jpg","original_url":"http:\/\/laravel-medialibrary-pro-app.robin\/storage\/6\/Q-only-fingerprint.png","order":1,"custom_properties":[],"extension":"png","size":39987}}`

**Comment by dseeger** [comment]
What you get from the demo app is $model->getMedia('my-collection');

What were you doing with the media data before you echo it?
