### ISSUE TITLE
Using with Bootstrap

### ISSUE THREAD

**Issue by GreenImp** [spatie/laravel-medialibrary-pro-app#15]
Hi,

We're using [Bootstrap-vue](https://bootstrap-vue.org) (Bootstrap CSS and Vue components) with a Laravel 7 project.
And we're hoping to use the Vue components from media library pro.

Will media library pro Vue components work alongside a Bootstrap project, or will the stylesheets conflict (I'm not sure if the styles are "scoped" to the components)?

**Comment by AdrianMrn** [comment]
Hi @GreenImp! We tested the components alongside Bootstrap 4, and we've done our best to make sure the components don't conflict. Let us know if you encounter any issues, and we'll try to resolve them for you!

**Comment by GreenImp** [comment]
That's brilliant, thanks!

**Comment by GreenImp** [comment]
Just wanted to say that I've been playing around with it a bit today and haven't found any issues. Thanks!
