### ISSUE TITLE
Hide / customise the "accepts" display

### ISSUE THREAD

**Issue by GreenImp** [spatie/laravel-medialibrary-pro-app#17]
Is there a way of either hiding or customising the text displayed for the list of accepted mime types?

I've got an input where we're accepting a reasonably wide range of different document types (Mainly different Word documents):
```
[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.oasis.opendocument.text',
    'text/plain',
]
```

But this can look quite messy in the attachment component:

<img width="535" alt="Screenshot 2021-01-06 at 13 44 57" src="https://user-images.githubusercontent.com/1846676/103775029-6432e080-5025-11eb-8473-8cb576970cdb.png">

Ideally I'd like to change it to something shorter, maybe something like:
> PDF or word document (e.g. '.pdf', '.doc', '.docx')

Is this possible? Or is there a better way of defining the accept mimes, that will display them in a more readable manner?

**Comment by freekmurze** [comment]
Could you please open up an issue at the media-library-pro repo. Issue on that repo follow a template that allow us to help you better.

**Comment by GreenImp** [comment]
@freekmurze did you mean on the https://github.com/spatie/laravel-medialibrary repo? I can't find another repo for the pro version (Other than one for the website, but that doesn't seem relevant)?

**Comment by freekmurze** [comment]
There also a repo for the pro version. You'll get access when you associate your GitHub account with your spatie.be account at spatie.be

If you don't have access after that, send us a mail at info@spatie.be

**Comment by GreenImp** [comment]
Okay, thanks. I don't have access to the Spatie account that purchased the license (Bought by my client), so I'll send an email over to you so we can discuss possible access.
