### ISSUE TITLE
Is it possible to have a thumbnail populate the edit field?

### ISSUE THREAD

**Issue by grantjanecek** [spatie/laravel-medialibrary-pro-app#20]
Using the default Vue component I would like the edit field to show the thumbnail. Is this possible out of box?

![image](https://user-images.githubusercontent.com/17169721/115879620-dd5d1480-a417-11eb-96ad-56dcedc95e03.png)

**Comment by AdrianMrn** [comment]
@grantjanecek Yes, this should be enabled out of the box (the demo on https://medialibrary.pro/demo-attachment are built using the Vue components).

Please set up the demo app on your machine (https://github.com/spatie/laravel-medialibrary-pro-app) and try to find the differences between your own app and the demo to debug why it's not working in your application.

Vue components can be found here: https://github.com/spatie/laravel-medialibrary-pro-app/tree/master/resources/js/vue and in blade here: https://github.com/spatie/laravel-medialibrary-pro-app/tree/master/resources/views/uploads/vue
