### ISSUE TITLE
Interested in Pro Version

### ISSUE THREAD

**Issue by skfaisal93** [spatie/laravel-medialibrary-pro-app#25]
I have a few queries regarding the Laravel Spatie Media library pro version.

1) Can I associate multiple models on a single media file? If possible can you please let me know how to do this?

2) How to upload media files without associating them with the models and then how can I retrieve those media files?

3) How to choose from pre-uploaded media files without uploading new media files?

4) How can I display all the uploaded media files?

**Comment by freekmurze** [comment]
> Can I associate multiple models on a single media file? If possible can you please let me know how to do this?

Currently this is not possible out of the box. If you need to do this you'll need to build your own pivot model between media and your own model.

> How to upload media files without associating them with the models and then how can I retrieve those media files?

This is currently not possible out of the box. You could associate a media with a dummy model (maybe called `TransientModel` or better).

3. How to choose from pre-uploaded media files without uploading new media files?

You could use the collection component for this, which displays all models that are saved in a media library collection.

4. How can I display all the uploaded media files?

The media library doesn't provide this out of the box, you need to build your own view for that.
