### ISSUE TITLE
Problem with app and PHP 8

### ISSUE THREAD

**Issue by Lerma4** [spatie/laravel-medialibrary-pro-app#28]
Hello,

is there a way to use the demo app with PHP 8? because when i try to run the "composer install" command the following error is displayed: 

Problem 1
    - spatie/pdf-to-image is locked to version 2.1.0 and an update of this package has not been requested.
    - spatie/pdf-to-image 2.1.0 requires ext-imagick * -> is missing on your system. Install or enable the PHP imagick extension.

The problem is that I think you cannot install this extension on PHP 8.

thanks

**Comment by freekmurze** [comment]
https://freek.dev/1845-building-the-imagick-php-extension-from-master
