### ISSUE TITLE
invalid uuid cant join the temp file to model

### ISSUE THREAD

**Issue by faxunil** [spatie/laravel-medialibrary-pro-app#29]
Hi!
I have a working Vue app.
Media is also uploaded file and SQL is present.
But If I want to join the uploaded file to my model I'm gettin UUID error.
After I have created the Event wanted to join the uploaded file
$event->addFromMediaLibraryRequest($request->get('media'))->toMediaCollection('tmp-xls');

"message": "invalid uuid",
"exception": "Exception",
"file": "/Users/gergelymac/gitrepos/cascade/vendor/spatie/laravel-medialibrary-pro/src/Dto/PendingMediaItem.php",
"line": 41,

Any Idea?
Br.
Gergely

**Comment by freekmurze** [comment]
Hi, could you compare what you got to how we our doing it in our demo application?
https://github.com/spatie/laravel-medialibrary-pro-app

**Comment by faxunil** [comment]
> Hi, could you compare what you got to how we our doing it in our demo application?
> https://github.com/spatie/laravel-medialibrary-pro-app

Hi!
Thank You yes I clonedt the example. 
The problem was a parameter in the PRO version.

If this :  '**enable_temporary_uploads_session_affinity**' => true, is true => UUID error. if false then OK.
Maybe You should point on that in the the config file and at the docs.
