### ISSUE TITLE
x-media-library-attachment not rendering correctly

### ISSUE THREAD

**Issue by alantucker** [spatie/laravel-medialibrary-pro-app#32]
The x-media-library-attachment tag is not rendering correctly, My version does not look like the [example on the website](https://spatie.be/docs/laravel-medialibrary/v9/images/pro/extra.png).

Looking in the browser console I am seeing the following errors, any ideas?

> app.js:2 Alpine Error: "TypeError: Cannot read properties of undefined (reading 'find')"
> 
> Expression: "initDropZone({ _this: window.livewire.find('K12tWpqGNw2YJSwWxeEI'), rules: '', multiple: '1', uploadError: '' })"
> Element: div.media-library-add
> 
> app.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'find')
>     at eval (eval at p.el (app.js:2), <anonymous>:3:92)
>     at p.el (app.js:2)
>     at p (app.js:2)
>     at d (app.js:2)
>     at new Ht (app.js:2)
>     at Object.initializeComponent (app.js:2)
>     at app.js:2
>     at app.js:2
>     at NodeList.forEach (<anonymous>)
>     at Object.discoverComponents (app.js:2)

Thanks in advance

Alan

**Comment by alantucker** [comment]
Thanks for your help. It's kinda rendering now but I am not getting the option to drag and drop on the reordering. Any ideas?

**Comment by AdrianMrn** [comment]
Are you getting any errors in your console when attempting to drag and drop, or when the component is loaded? Please set up the demo app (this repository), see if it works there and compare your setup to this one. Let me know if you need any further help with this!

**Comment by alantucker** [comment]
@AdrianMrn Thanks for the reply, I posted this in the wrong place, should have been in laravel-medialibrary-pro and not laravel-medialibrary-pro-app. I am how ever having [another issue](https://github.com/spatie/laravel-medialibrary-pro/issues/335).

**Comment by AdrianMrn** [comment]
No problem! Freek will continue looking at your problem in that issue!
