### ISSUE TITLE
Recent Error with $name

### ISSUE THREAD

**Issue by illusive-ch** [spatie/laravel-medialibrary-pro-app#34]
Using this code
```<x-media-library-attachment name="media" />``` 

I started receiving sporadic 500 errors
```
Illuminate\Contracts\Container\BindingResolutionException
Unable to resolve dependency [Parameter #1 [ <required> string $name ]] in class Spatie\MediaLibraryPro\Http\Livewire\LivewireUploaderComponent (View: /var/www/html/vendor/spatie/laravel-medialibrary-pro/resources/views/livewire/partials/thumb.blade.php)
```

The blade file will change depending on which implementation I am working on but it is always an issue with $name

**Comment by silas229** [comment]
Same issue here 🙋🏼‍♂️

**Comment by AdrianMrn** [comment]
@freekmurze Did we change anything that could cause this? @illusive-ch @silas229 have you tried `artisan optimize:clear`?

**Comment by silas229** [comment]
This has worked for me. Thank you!

**Comment by AdrianMrn** [comment]
Considering this fixed in that case! Let me know if you need further help with this.

**Comment by Bradzer** [comment]
Same issue here @AdrianMrn. 

Tried `php artisan optimize:clear` without success.

**Comment by AdrianMrn** [comment]
@Bradzer Could you please create a new issue here, filling out the template? This helps us to debug the problem! https://github.com/spatie/laravel-medialibrary-pro/issues/new?assignees=&labels=&template=bug_report.md&title=
