### ISSUE TITLE
Invalid uuid

### ISSUE THREAD

**Issue by khalilst** [spatie/laravel-medialibrary-pro-app#36]
[Sometimes] I've got this error from Media library:
```php
invalid uuid {"userId":1,"exception":"[object] (Exception(code: 0): invalid uuid at /var/www/html/vendor/spatie/laravel-medialibrary-pro/src/Dto/PendingMediaItem.php:41)
```

This is first lines of `laravel.log`:
```log
#0 /var/www/html/vendor/spatie/laravel-medialibrary-pro/src/MediaLibraryRequestHandler.php(73): Spatie\\MediaLibraryPro\\Dto\\PendingMediaItem->__construct()
#1 [internal function]: Spatie\\MediaLibraryPro\\MediaLibraryRequestHandler->Spatie\\MediaLibraryPro\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(664): array_map()
#3 /var/www/html/vendor/spatie/laravel-medialibrary-pro/src/MediaLibraryRequestHandler.php(75): Illuminate\\Support\\Collection->map()
#4 /var/www/html/vendor/spatie/laravel-medialibrary-pro/src/PendingMediaLibraryRequestHandler.php(95): Spatie\\MediaLibraryPro\\MediaLibraryRequestHandler->getPendingMediaItems()
```
The next line (from log) refers to this code:
```php
$model->addFromMediaLibraryRequest($attributes['something'])->toMediaCollection('something')
```

### Environment
Laravel 8.74
spatie/laravel-medialibrary-pro: 1.17
Media Disk: s3

**Comment by faxunil** [comment]
Hi!
I had prevoisly similar issue
try this: 

The problem was a parameter in the PRO version.

If this : 'enable_temporary_uploads_session_affinity' => true, is true => UUID error. if false then OK.

Br.

**Comment by plakhin** [comment]
`Invalid uuid` Exception is being thrown once one tries to save media collection before an image were (temporary) uploaded.
Can be reproduced with `Slow 3G` Throttling settings on the Network tab of Chrome Dev Tools.

Did anyone find a solution?

**Comment by plakhin** [comment]
This should help in my case:
https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/handling-uploads-with-vue#checking-the-upload-state
