### ISSUE TITLE
`FileIsTooBig` Exception

### ISSUE THREAD

**Issue by plakhin** [spatie/laravel-medialibrary-pro-app#38]
If a big file for some reason passes front-end validation, `FileIsTooBig` Exception is thrown.
This happens if web server and PHP limits are higher then media library config limit.

Example:

- On front-end we allow 100MB file to be uploaded (or don't use validation at all).
- Both, PHP max upload file size and nginx config allow files up to 100MB
- Media Library has the (default) limit of 10MB in config.
- We try to upload 50MB file.
- Exception is being thrown.

Can the uploaded file be validated with `'max:' . config('media-library.max_file_size')/1024` rule? This way we can have `422` Response that cab be parsed on front-end instead of `500` Response.  

@freekmurze what do you think?

**Comment by freekmurze** [comment]
Yeah, that makes sense to me. Feel free to PR this.

**Comment by plakhin** [comment]
@freekmurze how can I PR to the Media Library Pro?
I'm actually the Media Library Pro user, just didn't find another place to submit an issue.

**Comment by freekmurze** [comment]
If you connect your spatie.be account to GitHub, you'll have access to this repo https://github.com/spatie/laravel-medialibrary-pro 👍

**Comment by plakhin** [comment]
My Spatie account connected to GitHub, but Media Library Pro was bought from my teammate's account. 
Is there a way in this case?

**Comment by plakhin** [comment]
@freekmurze,

`'file' => 'max:' . config('media-library.max_file_size') / 1024,`
this validation rule should be added to `Spatie\MediaLibraryPro\Request\UploadRequest`

updated code should be:
```php
    public function rules(): array
    {
        return [
            'uuid' => "unique:{$this->getDatabaseConnection()}{$this->getMediaTableName()}",
            'name' => '',
            'custom_properties' => '',
            'file' => 'max:' . config('media-library.max_file_size') / 1024,
        ];
    }
```

Tested, works as needed.

Or is there a way to do this validation outside of the package?
The only way I see - is to manually create the `media-library-uploads` route that will point to the custom Controller that extends your Controller but requires custom `FormRequest` extended from your `UploadRequest` and that new `FormRequest` should rewrite `rules()` method with a new one that includes this new rule. 
Seems to much for a small rule addition.

**Comment by freekmurze** [comment]
Could you let your teammate PR this to the package?

**Comment by plakhin** [comment]
I'll try

**Comment by plakhin** [comment]
@freekmurze the PR was submitted.
