### ISSUE TITLE
Documented "MediaLibraryRequestItem" does not exist

### ISSUE THREAD

**Issue by jsteve1993** [spatie/laravel-medialibrary-pro-app#41]
The documentation says to use "Spatie\MediaLibraryPro\MediaLibraryRequestItem" to get properties of the uploaded file but this class does not seem to exist in the source.

**Comment by jsteve1993** [comment]
Found it at "Spatie\MediaLibraryPro\Dto\MediaLibraryRequestItem" - could the docs please be updated?

Thanks!

**Comment by freekmurze** [comment]
Thanks for reporting. There's an edit button on top of each page in the docs. You can use that to create a PR to fix it 👍
