### ISSUE TITLE
Thumbnails not working. Also having issues with pdf

### ISSUE THREAD

**Issue by drduby** [spatie/laravel-medialibrary-pro-app#42]
Dear Support,
 
we bought the Pro Version of Media-Library-Pro and we are having troubles to make it run.
I execute all the instructions as it is described at the Documentation.
I also tried to run the Demo-Project of yours. https://github.com/spatie/laravel-medialibrary-pro-app. In this case GUI is working but thumbnails are not working. I also have troubles when I try to upload a .pdf. Even if pdf is allowed as a format to upload is throwing me an Exception
 
Our Environment:
PHP 7.4.5
Homestead
 
While trying upload an Image:
![pic_1](https://user-images.githubusercontent.com/8825678/156731570-a3117d67-3b45-45cf-a147-233213960f66.png)

![pic_2](https://user-images.githubusercontent.com/8825678/156731643-62ac9833-7a35-45c0-9920-ccbfe1d02fee.png)

![pic_3](https://user-images.githubusercontent.com/8825678/156731741-9210a30b-ea8d-4570-b83a-031124b588d9.png)

Thank you.
 
Best regards
Gent

**Comment by MCKLtech** [comment]
I tried to get this to work for a week and gave up in the end. My suspicion is that you need additional libraries in PHP to convert them but even with everything installed, it didn't work.

**Comment by Hnooz** [comment]
try to register preview conversion to your model 

`
public function registerMediaConversions(Media $media = null): void {
        $this->addMediaConversion('preview');
}
`

**Comment by mplank** [comment]
try this: `php artisan storage:link`
