### ISSUE TITLE
Original URL no longer being returned

### ISSUE THREAD

**Issue by SuryaWebfox** [spatie/laravel-medialibrary-pro-app#44]
I just updated from Medialibrary Pro 2.1.6 to 2.1.8 and the `MediaLibraryUploadController.php` no longer returns the `original_url` which I need in my application.

Is there a setting I can add to have that included in the response?

**Comment by freekmurze** [comment]
There's not setting for that. You could achieve this by not using the `mediaLibrary` macro, but manually registering [the route that the macro registers under the hood](https://github.com/spatie/laravel-medialibrary-pro/blob/3fdfa93e786208e5045e112801dc18defc0d4898/src/MediaLibraryProServiceProvider.php#L106).

You should create a controller of your own, let it extend the `MediaLibraryUploadController` and you should override [the `responseFields` function](https://github.com/spatie/laravel-medialibrary-pro/blob/c02a04d18cc2b118cff96ae9e6d1a11fe0c2f743/src/Http/Controllers/MediaLibraryUploadController.php#L40) that was just added in the latest version of the package.

**Comment by SuryaWebfox** [comment]
Well, that's rather inconvenient. I'd like to understand why that value was removed on what is essentially a bugfix release? Isn't this a breaking change? Or did I miss something?

**Comment by freekmurze** [comment]
Returning the original URL by default was considered a security issue.

**Comment by SuryaWebfox** [comment]
Thanks for the clarification
