### ISSUE TITLE
Livewire component is all janky and slow

### ISSUE THREAD

**Issue by ryanmortier** [spatie/laravel-medialibrary-pro-app#45]
Is there a way to defer wire model updates because as you can see in the attached video, the user experience can be pretty disruptive.

https://user-images.githubusercontent.com/2053960/159998581-b9a1c7d1-4083-4301-a075-d4abe6b8c460.mp4

**Comment by ryanmortier** [comment]
This issue was meant for the `spatie/laravel-medialibrary-pro` repo. Closing.

**Comment by michaellatham** [comment]
Hi, did you manage to sort this? I looked on the `spatie/laravel-medialibrary-pro` repo but couldn't find your issue. My issue is that it keeps randomly deleting characters as I type, presumably on a keyup callback

**Comment by michaellatham** [comment]
@ryanmortier

**Comment by ryanmortier** [comment]
> @ryanmortier

No, I stopped using the pro components altogether.
