### ISSUE TITLE
I have lost the way to get the URLs after buy the PRO version

### ISSUE THREAD

**Issue by andrecuellar** [spatie/laravel-medialibrary-pro-app#46]
I bought the pro version because it offered an easy way to implement a drag & drop using livewire, before I used the free version, but now I have a lot of problems with this library:
1) Clicking on "select a file" opens the image selection window twice, it could be my problem, I'll leave it for later
2) Since I installed the PRO version, I can no longer get the URL of any of my images and the PRO version documentation doesn't say anything about that

My old code

```
$user = Auth::user();
        $validatedData = $this->validate();
        if ($this->avatar) {
            $media = $user->addMedia($this->avatar->getRealPath())
                ->preservingOriginal()
                ->usingName($this->avatar->getClientOriginalName())
                ->toMediaCollection('avatars');
            $validatedData['avatar'] = $media->getUrl();
        }
```

my new code

```
        $userId = Auth::id();
        $user = User::find($userId);
        $validatedData = $this->validate();
        if ($this->avatar) {
             $user->addFromMediaLibraryRequest($this->avatar)
                ->toMediaCollection('avatars');
        }
```

```$user->getMedia()``` returns null

**Comment by espradley** [comment]
@andrecuellar Did you ever figure it out.  I'm having the exact same issue.  Select image opens twice and the temp upload doesn't work.  I'm using livewire, but tried without livewire too.
