### ISSUE TITLE
Upgrading to Laravel 9.8

### ISSUE THREAD

**Issue by rtaylor82** [spatie/laravel-medialibrary-pro-app#48]
Using laravel shift, but still dependency issues: 

root@44a185dc9ce5:/var/www/html# composer update -W
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v9.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.1 (conflict analysis result)
    - illuminate/validation[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.11) does not satisfy that requirement.
    - illuminate/validation[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.11) does not satisfy that requirement.
    - spatie/laravel-medialibrary-pro[1.17.5, ..., v1.x-dev] require illuminate/validation ^8.71 -> satisfiable by illuminate/validation[v8.71.0, ..., 8.x-dev].
    - spatie/laravel-medialibrary-pro 1.17.4 requires illuminate/validation ^7.25|^8.0 -> satisfiable by illuminate/validation[v7.25.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/validation[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.8.0, v9.8.1, 9.x-dev]. laravel/framework replaces illuminate/validation and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.8 -> satisfiable by laravel/framework[v9.8.0, v9.8.1, 9.x-dev].
    - Root composer.json requires spatie/laravel-medialibrary-pro ^1.17.4 -> satisfiable by spatie/laravel-medialibrary-pro[1.17.4, ..., v1.x-dev].

root@44a185dc9ce5:/var/www/html# composer update --ignore-platform-reqs
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v9.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.1 (conflict analysis result)
    - spatie/laravel-medialibrary-pro[1.17.5, ..., v1.x-dev] require illuminate/validation ^8.71 -> satisfiable by illuminate/validation[v8.71.0, ..., 8.x-dev].
    - spatie/laravel-medialibrary-pro 1.17.4 requires illuminate/validation ^7.25|^8.0 -> satisfiable by illuminate/validation[v7.25.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/validation[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.8.0, v9.8.1, 9.x-dev]. laravel/framework replaces illuminate/validation and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.8 -> satisfiable by laravel/framework[v9.8.0, v9.8.1, 9.x-dev].
    - Root composer.json requires spatie/laravel-medialibrary-pro ^1.17.4 -> satisfiable by spatie/laravel-medialibrary-pro[1.17.4, ..., v1.x-dev].

Not sure how to proceed... Seems pro requires illuminate/validation but latest version of Laravel negates that...

**Comment by rtaylor82** [comment]
Nevermind, switching to version 2 solved the problem: 

"spatie/laravel-medialibrary-pro": "^2.0.0",

**Comment by AtlasApollo** [comment]
Thank you for that @rtaylor82, it helped me install Media Library Pro :)
