### ISSUE TITLE
orphaned folders/files on disk

### ISSUE THREAD

**Issue by topegret** [spatie/laravel-medialibrary-pro-app#54]
I test this mdialibrary pro demo app by follow the instruction and using all default settings:
in the config/media-library.php 
`  'disk_name' => env('MEDIA_DISK', 'public'),
`
and config/filesystems.php 
```
'disks' => [
   ...
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```
I have run artisan storage:link as well. 

I noticed that the actually media files were uploaded to the storage/app/public folder like this.  
![image](https://user-images.githubusercontent.com/10137853/180625077-65145c10-dda9-4c01-8633-334cb280a1e4.png)

it seems to me correctly uploaded file is in the folder named as the Media model id which is make sense .  but for some reason those not correctly uploaded or yet been uploaded files are been saved in a uuid type  of folder name(temporary folders?). I have no idea how to remove those unused folders/files in the future. According to the instruction:
_#Automatically removing temporary uploads
If you are using Media Library Pro, you must schedule this artisan command in app/Console/Kernel to automatically delete temporary uploads
// in app/Console/Kernel.php
protected function schedule(Schedule $schedule)
{
    $schedule->command('media-library:delete-old-temporary-uploads')->daily();
}_  

But  I have tested  it manually "php artisan media-library:delete-old-temporary-uploads". not able to actually delete those files .  I also create a command similar to this  but I have   
```
$temporaryUploads = $temporaryUploadModelClass::all();
            $temporaryUploads->each->delete();  
```
by using this tool I am able to clean the "temporay_uplodads" table and remove records which have temp model_type in the media table. but still I am not able to clean those orphaned folders. would this  put junks folder and file on my disk ? 

thanks!

**Comment by gingebaker** [comment]
https://github.com/spatie/laravel-medialibrary-pro/issues/460#issuecomment-1204051247
