### ISSUE TITLE
Progress bar shows progress only when files are dropped, not when they're selected

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/laravel-medialibrary-pro-app#61]
Laravel: `9.43.0`
Media Library Pro: `2.6.1`

When I drag and drop media files the progress bar indicates the process, when I click to select files it doesn't. See screen recording attached:

https://user-images.githubusercontent.com/5268113/207840919-b7d0297e-173c-439c-a987-0e1727def01a.mov

**Comment by LeeJump24** [comment]
@joostvanhoof Did you ever get a response? I have come across this bug also.
