### ISSUE TITLE
Other input types on custom properties?

### ISSUE THREAD

**Issue by dink** [spatie/laravel-medialibrary-pro-app#67]
The demo app provides an option to set custom properties via an `input type="text"` field. Is there a way to have a checkbox, radio, or something similar instead? I just need a simple boolean option to mark certain items, and would rather not type it out every time. 

If there is, how would I go about accomplishing this?

Cheers

**Comment by richardjkeys** [comment]
I've also tried with a textarea and although it saved the value to the database, it wasn't filled when the page refreshed. Would be extremely useful for basic input types to be supported.

**Comment by levipeto** [comment]
<textarea
        class="media-library-input"
        rows="5"
        {{ $mediaItem->livewireCustomPropertyAttributes('description') }}
    >{{ $mediaItem->customPropertyAttributeValue('description') }}</textarea>
