### ISSUE TITLE
Vue tests failing

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary-pro-app#7]
The Vue tests seems to be failing. 
https://github.com/spatie/laravel-medialibrary-pro-app/runs/1439095722?check_suite_focus=true#step:10:898

Probably something small, could you take a look at that @AdrianMrn ?

**Comment by AdrianMrn** [comment]
This was related to https://github.com/spatie/laravel-medialibrary-pro/issues/74 and is now fixed 👍
