### ISSUE TITLE
Livewire 3 support

### ISSUE THREAD

**Issue by bandomesic** [spatie/laravel-medialibrary-pro-app#74]
HI Spatie team,

did you consider to prepare pro package for Livewire 3. I'm getting strange errors like this one when try to use package:

1. "Method Spatie\MediaLibraryPro\Http\Livewire\LivewireUploaderComponent::emit does not exist."

2. "Spatie\MediaLibraryPro\Actions\ConvertLivewireUploadToMediaAction::execute(): Argument #1 ($temporaryUploadedFile) must be of type Livewire\TemporaryUploadedFile, Livewire\Features\SupportFileUploads\TemporaryUploadedFile given, called in /var/www/html/vendor/spatie/laravel-medialibrary-pro/src/Http/Livewire/LivewireUploaderComponent.php on line 104"

I think there are not so many changes that you should do to be ready for Livewire 3 :)

**Comment by freekmurze** [comment]
We're currently working on support v3. You can expect a release in the next few weeks.
