### ISSUE TITLE
Don't see validation error message with collection, please help

### ISSUE THREAD

**Issue by lingtalfi** [spatie/laravel-medialibrary-pro-app#85]
I'm using the collection component in my blade template:

  <x-media-library-collection
        name="documents"
        :model="$transport"
        max-items="3"
        rules="mimes:png,jpeg,pdf|max:3000"
/>

Posting an item with empty name (testing validation), i don't see the validation error message anywhere !

It's there, as demonstrated by the debug statement:

`dd($errors)`

result: 

```
Illuminate\Support\ViewErrorBag {#2196 ▼ // resources/views/events/manager/transport/edit.blade.php
  #bags: array:1 [▼
    "default" => 
Illuminate\Support\MessageBag {#2197 ▼
      #messages: array:1 [▼
        "documents.41c99952-ea8c-4315-a5f2-79dd72f7f40d.name" => array:1 [▼
          0 => "name est obligatoire."
        ]
      ]
      #format: ":message"
    }
  ]
}
```

But it doesn't show in the page, as you can see below (form posted):

<img width="490" alt="image" src="https://github.com/spatie/laravel-medialibrary-pro-app/assets/223667/b523b927-43ad-472c-ab58-357ff0192f79">

What i would like to have is nice validation error messages, the same that we have in the demo (https://medialibrary.pro/demo-collection): 

<img width="698" alt="image" src="https://github.com/spatie/laravel-medialibrary-pro-app/assets/223667/7d26c8f8-c8e3-435f-a727-909c5b02c029">

Trying to search for validation in the docs, but i don't see much, apart from this page: https://spatie.be/docs/laravel-medialibrary/v11/handling-uploads-with-media-library-pro/processing-uploads-on-the-server.

Is there another doc page for validation? I didn't found much on the subject. 

Anyway, do you have any idea why my setup doesn't trigger the validation error message? 

Thanks for your help.

----UPDATE: i forgot to post my setup:

I have my model prepared:

```php
<?php

namespace App\Models\EventManager\Transport;


use Illuminate\Database\Eloquent\Model;
use Spatie\Image\Enums\Fit;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class EventTransport extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $guarded = [];
    protected $table = 'event_transports';

    public function registerMediaConversions(Media $media = null): void
    {
        $this
            ->addMediaConversion('preview')
            ->fit(Fit::Contain, 300, 300)
            ->nonQueued();
    }
}
```

My controller basically looks like this:

```php
public function updateByEventContact(EventTransportRequest $request, EventContact $eventContact)
{
      $this->transport
        ->syncFromMediaLibraryRequest($request->documents)
        ->toMediaCollection();

        $this->transport->save();
        //...
}     
```   

In my FormRequest i have these rules:

```php
    public function rules()
    {
        return [
            'documents' => $this
                ->validateMultipleMedia()

                ->minItems(1)
                ->maxItems(5)
                ->extension('png')
                ->maxItemSizeInKb(1024)
                ->itemName(['required', 'string', 'max:255']),
        ];
    }
```

I also tried with this:
```
            'documents' => $this
                ->validateMultipleMedia()
                
                ->minItems(1)
                ->maxItems(5)
                ->extension('png')
                ->maxItemSizeInKb(1024)
                ->attribute('name', 'required'),
```

Note: regular upload works, it's just the validation error message that doesn't show up at the ui level.

**Comment by roesware** [comment]
I've got the exact same issue, got any updates or fixes? :)
