### ISSUE TITLE
Issues when deployed

### ISSUE THREAD

**Issue by Design2k** [spatie/laravel-medialibrary-pro-app#88]
Everything is working locally with media library pro however once deployed we get this error.  Any help will be great.

![IMG_9644](https://github.com/spatie/laravel-medialibrary-pro-app/assets/94699101/0675dca4-041f-4701-87c1-4a2e5c908ecf)

**Comment by vishalinfyom** [comment]
Hi @Design2k 

I resolved it via the SSH panel.

1. Login to ssh panel
2. Goto your project path (`/var/www/html/`)
3. Remove the vendor folder if you already added (`rm -rf vendor`)
4. Run `composer install`
5. It will ask for spatie username & password, add it properly and enter.

That's it.

**Comment by Design2k** [comment]
Great! Thank you!
