### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by amshehzad** [spatie/laravel-medialibrary-pro-app#89]
Does this support laravel 11 yet? as I tried and couldn't install on laravel 11

Thanks

**Comment by marknuyens** [comment]
I agree, I can't seem to fix this either. Without sounding cynical, I do find these kinds of issues pretty obtrusive. I realize there are rules designed to ensure stability, security and what not, but simply upgrading Laravel is not simple at all.

If you have to wait for all kinds of packages to update their `composer.json` file to continue upgrading your application, there's seriously something wrong with this workflow.

Sorry for this rant, but can't help but sense a big elephant in the room (no pun intended) that nobody seems to address. I've heard about forking packages and doing all kinds of hacky stuff to manage these conflicts, but these don't seem to suffice.

I am really hoping the PHP/Composer community steps up its game to address these kinds of obvious road blocks.

**Comment by williamengbjerg** [comment]
Hey @amshehzad, I can upgrade to version 11 by simply adding the following line to my composer.

`"spatie/laravel-medialibrary-pro": "@stable"`
