### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by SquareNetMedia** [spatie/laravel-medialibrary-pro-app#92]
I'm getting an error

Call to undefined method Spatie\MediaLibraryPro\PendingMediaLibraryRequestHandler::withResponsiveImages()

When I am trying to add in responsive images to my code using

$formSubmission
            ->addFromMediaLibraryRequest($this->postimages)
            ->withResponsiveImages()
            ->toMediaCollection('post-images');

**Comment by timvandijck** [comment]
For isues with the package please use: https://github.com/spatie/laravel-medialibrary-pro/issues
