### ISSUE TITLE
Reset of media-library-attachment component in VUE

### ISSUE THREAD

**Issue by eposwiatny** [spatie/laravel-medialibrary-pro-app#93]
Hello,

In my VueJS project I'm using Media library Pro package that contain components for file upload. 

I would like to know if is it possible to manually trigger form reset? I mean, when user add file, it can remove it by clicking "remove" button but I would like to trigger it manually trought another button.

![Screenshot 2024-05-01 at 00 29 20](https://github.com/spatie/laravel-medialibrary-pro-app/assets/32684030/ef4a3d1d-a16d-4523-9a13-fc591be929c8)

From what I see, any informations about it are present in documentation. I tried by reset REF that store file information but component still display added file

**Comment by timvandijck** [comment]
For isues with the package please use: https://github.com/spatie/laravel-medialibrary-pro/issues
